name: EXSi_67_sata_Net-net-igb
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: 'EXSi_67_sata-net-igb'
      driver:
        description: 'Driver Name'
        required: true
        default: 'net-igb'
        
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
    
      - name: Download ESXi-Customizer-PS Script
        shell: powershell
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile('https://github.com/VFrontDe/ESXi-Customizer-PS/archive/refs/tags/2.9.0.zip','ESXi-Customizer-PS.zip')
          Expand-Archive -Path ESXi-Customizer-PS.zip -DestinationPath ./
          cd ESXi-Customizer-PS-2.9.0
          $env:WORK_DIR=$PWD
          $env:WORK_DIR
          echo "WORK_DIR=$env:WORK_DIR" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      - name: Install VMware.PowerCLI and Python dependency
        shell: powershell
        run: |
          #Install-Module -Name VMware.PowerCLI -AcceptLicense -Force -SkipPublisherCheck
          pip3.exe install six psutil lxml pyopenssl
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser -Force
          Get-ExecutionPolicy
          scripts\Install_PowerCli.ps1
           
      - name: Export exsi6.7 base image from Online ImageProfile
        shell: powershell
        run: |
          cd $env:WORK_DIR\
          Add-EsxSoftwareDepot https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/vmw-depot-index.xml
          Get-EsxImageProfile |  ft Name | findstr "ESXi-6.7.0" | findstr "standard" > names.txt
          $NAME = (Get-Content .\names.txt -TotalCount 1)
          Export-ESXImageProfile -ImageProfile $NAME -ExportToBundle -filepath ESXi-6.7.0-standard.zip
          
      - name:  Generate EXSi ISO File
        shell: powershell
        run: |
          cd $env:WORK_DIR\
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser -Force
          .\ESXi-Customizer-PS.ps1 -izip .\ESXi-6.7.0-standard.zip -nsc -v67 -vft -load sata-xahci,net-igb -ipname ${{ github.event.inputs.tag }} -outDir ..\ -log ..\build-log.txt
          dir ..\
         
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          name: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            build-log.txt
            ${{ github.event.inputs.tag }}.iso
