name: EXSi_67_sata_Net55-r8168_nvme_usb
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: 'EXSi_67_sata_Net55-r8168_nvme_usb'
      driver:
        description: 'Driver Name'
        required: true
        default: 'r8168_nvme_usb_sata'
        
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
          
      - name: Download ESXi-Customizer-PS Script
        shell: powershell
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile('https://github.com/VFrontDe/ESXi-Customizer-PS/archive/refs/tags/2.9.0.zip','ESXi-Customizer-PS.zip')
          Expand-Archive -Path ESXi-Customizer-PS.zip -DestinationPath ./
          cd ESXi-Customizer-PS-2.9.0
          $env:WORK_DIR=$PWD
          $env:WORK_DIR
          echo "WORK_DIR=$env:WORK_DIR" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install VMware.PowerCLI and Python dependency
        shell: powershell
        run: |
          # Install-Module -Name VMware.ImageBuilder -AcceptLicense -Force -SkipPublisherCheck (This takes too too long time. , so I use offline pkgs to install it)
          pip3.exe install six psutil lxml pyopenssl
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser -Force
          Get-ExecutionPolicy
          #replaced "Install-Module -Name VMware.ImageBuilder" to install the commands we need to build iso, more info https://www.powershellgallery.com/packages/VMware.ImageBuilder/8.0.0.20817746
          scripts\Install_PowerCli.ps1
          
           
      - name: Download exsi6.7 Base image
        shell: powershell
        run: |
          cd $env:WORK_DIR\
          Add-EsxSoftwareDepot https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/vmw-depot-index.xml
          Export-ESXImageProfile -ImageProfile "ESXi-6.7.0-20221004001-standard" -ExportToBundle -filepath ESXi-6.7.0-20221004001-standard.zip
          
      - name:  Generate EXSi ISO File
        shell: powershell
        run: |
          cd $env:WORK_DIR\
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser -Force
          #.\ESXi-Customizer-PS.ps1 -izip .\ESXi-6.7.0-20221004001-standard.zip -nsc -log ..\build-log.txt -v67 -vft -load sata-xahci,net55-r8168 -pkgDir ..\drivers -ipname ${{ github.event.inputs.tag }} -outDir ..\
          .\ESXi-Customizer-PS.ps1 -izip .\ESXi-6.7.0-20221004001-standard.zip -nsc -log ..\build-log.txt -v67 -pkgDir ..\drivers\67\ -ipname ${{ github.event.inputs.tag }} -outDir ..\
          dir ..\
         
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          name: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            build-log.txt
            ${{ github.event.inputs.tag }}.iso
