name: Generate EXSi Customized ISO
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: 'ESXi-Customized-ISO'
      driver:
        description: 'Driver Name'
        required: true
        default: 'net55-r8168'
        
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
      
      - name: Python Check
        shell: powershell
        run: |
          C:\hostedtoolcache\windows\Python\3.7.9\x64\bin\python.exe --version
          C:\hostedtoolcache\windows\Python\3.7.9\x64\bin\pip.exe --verion
        
      - name: Download ESXi-Customizer-PS Script
        shell: powershell
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile('https://github.com/VFrontDe/ESXi-Customizer-PS/archive/refs/tags/2.9.0.zip','ESXi-Customizer-PS.zip')
          Expand-Archive -Path ESXi-Customizer-PS.zip -DestinationPath ./
          cd ESXi-Customizer-PS-2.9.0
          $env:WORK_DIR=$PWD
          $env:WORK_DIR
          echo "WORK_DIR=$env:WORK_DIR" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install VMware.PowerCLI
        shell: powershell
        run: 
          Set-PowerCLIConfiguration -Scope User -ParticipateInCEIP $false
          Install-Module -Name VMware.PowerCLI -AcceptLicense -Force -SkipPublisherCheck
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
          Set-PowerCLIConfiguration -PythonPath "C:\hostedtoolcache\windows\Python\3.7.9\x64\bin\python.exe" -Scope User
        
      - name: Python env setup for VMware.PowerCLI
        shell: powershell
        run: |
          C:\hostedtoolcache\windows\Python\3.7.9\x64\bin\pip3.exe install six psutil lxml pyopenssl

      - name:  Generate EXSi ISO File
        shell: powershell
        run: |
          cd $env:WORK_DIR\
          .\ESXi-Customizer-PS.ps1 -nsc -v60 -vft -load ${{ github.event.inputs.driver }},sata-xahci -ipname ${{ github.event.inputs.tag }}_${{ github.event.inputs.driver }} -outDir ..\
          dir ..
         
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          name: ${{ github.event.inputs.tag }}_${{ github.event.inputs.driver }}
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            ${{ github.event.inputs.tag }}_${{ github.event.inputs.driver }}.iso
